feat(fscomponents): Replace all occurrences of "any" in LocationItem
brandingbrand/flagship pull request #1353
Opened 2020-05-07 12:12 UTC by alexandrvlasov

## Description
Replace all occurrences of "any" in LocationItem

2020-09-21 17:27 UTC, bweissbart commented
@alexandrvlasov - looks good but conflicts :(

2020-09-21 17:28 UTC, bweissbart requested changes
conflicts

2020-09-23 09:37 UTC, alexandrvlasov commented
@bweissbart Conflicts resolved.

2020-09-23 20:45 UTC, bweissbart approved these changes

2020-09-23 20:45 UTC, merged