feat: Update FS component to allow custom header to be passed in
brandingbrand/flagship pull request #1594
Opened 2020-08-18 10:17 UTC by Bodrus

## Description
Update FS component to allow custom header to be passed in

2020-09-16 20:18 UTC, bweissbart requested changes
@Bodrus - I believe what is actually needed here is for the ability to pass in an entirely different header component. I'd recommend adding a new optional prop to EngagementComp (called something like `renderHeader` that accepts a function that returns JSX. If this prop is provided, it will call that function instead of rendering the default "welcome" header.

2020-09-17 13:24 UTC, Bodrus commented
@bweissbart Changed and tested! Please look

2020-09-22 19:49 UTC, Cauldrath commented on packages/fsengagement/src/EngagementComp.tsx
> +          Hello{comma}{name}
While this does look good overall, this is changing the default behavior of the component. Adding `textTransform: uppercase` to styles.headerName should make it act the same.

2020-09-23 14:33 UTC, Bodrus commented
@Cauldrath Fixed!

2020-09-23 15:26 UTC, Cauldrath approved these changes
Seems good.

2020-09-23 15:26 UTC, merged