feat: complex activations
brandingbrand/flagship pull request #2230
Opened 2021-09-17 20:41 UTC by wSedlacek

## Description

This allows guarding activations
This allows using params in redirects

2021-09-20 17:22 UTC, wSedlacek commented
Relating to the CI error 🤔 
```
/home/travis/build/brandingbrand/flagship/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 405 <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

2021-09-20 19:21 UTC, nathan-sankbeil approved these changes
Seems to work as expected.

2021-09-21 18:51 UTC, bweissbart requested changes
CI issues as noted separately

2021-09-27 17:41 UTC, bweissbart approved these changes

2021-09-27 17:42 UTC, merged