fix: exported currency value from it's own type file instead of index
brandingbrand/flagship pull request #2327
Opened 2021-11-22 15:52 UTC by chrisjlan89

2021-11-24 16:06 UTC, bweissbart approved these changes

2021-11-29 18:02 UTC, bweissbart requested changes

2021-11-29 18:02 UTC, bweissbart commented on packages/fscommerce/src/Commerce/CommerceTypes.ts
> +export * from './types/CurrencyValue'
Need a semicolon here.

2021-12-01 21:52 UTC, wSedlacek commented on packages/fscommerce/src/Commerce/CommerceTypes.ts
> +export * from './types/CurrencyValue'
```suggestion
export * from './types/CurrencyValue';
```

2021-12-02 16:26 UTC, bweissbart approved these changes

2021-12-02 16:26 UTC, merged