feat(doc) adding workflow to deploy docs
brandingbrand/flagship pull request #2556
Opened 2023-03-10 15:19 UTC by jasonmosley

2023-03-10 15:30 UTC, jasonmosley commented
@crherman7 We will need to update the config

```
export default defineConfig({
  site: 'https://brandingbrand.github.io',
  base: '/flagship',
})
```

2023-03-10 15:38 UTC, jasonmosley commented
@xero I could have used the ` withastro/action@v0` but didn't know if we had a policy about using actions not maintained by github? If we can use astros action it would simplify the workflow.

2023-03-10 17:42 UTC, xero commented
> @xero if we had a policy about using actions not maintained by GitHub & if we can use Astros actions

yes you can, but please pin the hash not the tag

2023-03-10 17:56 UTC, jasonmosley commented
@crherman7  can you test this to ensure I covered all the URL changes needed?

2023-03-15 16:54 UTC, crherman7 requested changes
Also look for paths in the `.md` and `.mdx` files - they are also missing the prefix

2023-03-15 16:54 UTC, crherman7 commented on docs/src/lib/config.ts
> +      link: "en/packages/plugins/native-navigation",
`/flagship/`

2023-03-15 16:54 UTC, crherman7 commented on docs/src/lib/config.ts
> +      link: "en/packages/plugins/target-extension",
`/flagship/`

2023-03-20 20:05 UTC, crherman7 commented
```
[dev] Requests for items in your public folder must also include your base. /flagship-code--dark.svg should be /flagship/flagship-code--dark.svg. Omitting the base will break in production.
```

we also need to prepend every public asset with `/flagship/`

2023-03-21 22:09 UTC, jasonmosley commented
This ready for review

2023-03-21 22:24 UTC, xero approved these changes
👁️👁️👍

2023-03-24 14:26 UTC, crherman7 approved these changes

2023-03-24 14:27 UTC, merged