feat(cli): fsapp v10 env export default
brandingbrand/flagship pull request #2710
Opened 2024-05-30 18:59 UTC by crherman7

## Describe your changes

## Issue ticket number and link

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Test Plan

## Checklist before requesting a review

- [ ] A self-review of my code has been completed
- [ ] Tests have been added / updated if required
- [ ] Documentation has been updated to reflect these changes

2024-06-03 20:01 UTC, NickBurkhartBB requested changes

2024-06-03 20:01 UTC, NickBurkhartBB commented on packages/cli/src/actions/env.ts
> +      // In fsapp <v10 the export is expected to be a default export
@crherman7 nitpick on comment <v11, otherwise good

2024-06-04 15:08 UTC, crherman7 commented on packages/cli/src/actions/env.ts
> +      // In fsapp <v10 the export is expected to be a default export
nice catch

2024-06-04 17:22 UTC, NickBurkhartBB approved these changes

2024-06-04 17:22 UTC, merged